export const ACCOUNT_TYPE = {
  ADMIN: "Admin",
  MEMBER: "Member",
  STUDENT: "Student", // legacy fallback
  INSTRUCTOR: "Instructor", // legacy fallback
};

export const SAMAJ_ROLES = {
  SUPER_ADMIN: "SUPER_ADMIN",
  MEMBER: "MEMBER",
  MODERATOR: "MODERATOR",
  TREASURER: "TREASURER",
  MATRIMONIAL_ADMIN: "MATRIMONIAL_ADMIN",
  SCHOLARSHIP_ADMIN: "SCHOLARSHIP_ADMIN",
  JOB_ADMIN: "JOB_ADMIN",
  DHARAMSHALA_ADMIN: "DHARAMSHALA_ADMIN",
  CONTENT_ADMIN: "CONTENT_ADMIN",
};

export const ACCOUNT_STATUS = {
  PENDING: "PENDING",
  ACTIVE: "ACTIVE",
  SUSPENDED: "SUSPENDED",
  REJECTED: "REJECTED",
  CORRECTION_REQUESTED: "CORRECTION_REQUESTED",
  DEACTIVATED: "DEACTIVATED",
  BANNED: "BANNED",
};

export const PRIVACY_LEVELS = {
  PUBLIC: "PUBLIC",
  MEMBERS_ONLY: "MEMBERS_ONLY",
  PRIVATE: "PRIVATE",
};
